admin_prostooremonte:
    resource: "@AdminProstooremonteBundle/Controller/"
    type:     annotation
    prefix:   /secure-admin

site_prostooremonte:
    resource: "@SiteProstooremonteBundle/Controller/"
    type:     annotation
    prefix:   /
