admin_prostooremonte:
    resource: "@AdminProstooremonteBundle/Resources/config/routing.yml"
    prefix:   /

prostooremonte:
    resource: "@ProstooremonteBundle/Resources/config/routing.yml"
    prefix:   /
